version: '3.5'

services:
  prisma_add_migration:
    container_name: prisma_add_migration
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile.migrate
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./prisma:/app/prisma
    tty: true
    stdin_open: true
    command:
      [
        "./create-migration.sh",
        "$DB_HOST",
        "$POSTGRES_USER",
        "$MIGRATION_NAME"
      ]

  db:
    container_name: postgres_container
    build: ./docker/postgres
    env_file:
      - .env
    volumes:
      - postgres:${PGDATA}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_USER}",
          "-d",
          "${POSTGRES_DB}"
        ]
    restart: unless-stopped

volumes:
  postgres:
