version: '3.5'

services:
  prisma_migrate:
    container_name: prisma_migrate
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile.migrate
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: postgres_container
    build: ./docker/postgres
    env_file:
      - .env
    volumes:
      - postgres:${PGDATA:-/data/postgres}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_USER:-postgres}",
          "-d",
          "${POSTGRES_DB:-postgres_db}"
        ]
    restart: unless-stopped

volumes:
  postgres:
