version: '3.5'

services:
  nest:
    container_name: nest_container
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
    networks:
      - postgres
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    container_name: postgres_container
    build: ./postgres
    env_file:
      - .env
    volumes:
      - postgres:${PGDATA:-/data/postgres}
    networks:
      - postgres
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_USER:-postgres}",
          "-d",
          "${POSTGRES_DB:-postgres_db}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  pg_admin:
    container_name: pgadmin_container
    build: ./pgadmin
    env_file:
      - .env
    volumes:
      - pgadmin:${PGADATA:-/var/lib/pgadmin}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
