FROM node:21-alpine

RUN echo $DATABASE_URL

WORKDIR /app

RUN apk update
RUN apk add postgresql-client

COPY ./package.json ./
COPY ./prisma ./prisma/

RUN yarn install
RUN yarn prisma generate

COPY ./bash/migrate-postgres.sh ./
RUN chmod +x ./migrate-postgres.sh

CMD ./migrate-postgres.sh $DB_HOST $POSTGRES_USER 