version: '3.5'

services:
  
  db:
    container_name: postgres_container
    build: ./postgres
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_DB: ${POSTGRES_DB:-postgres_db}
      PGDATA: ${PGDATA:-/data/postgres}
    volumes:
      - postgres:${PGDATA:-/data/postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - postgres
    restart: unless-stopped

  pg_admin:
    container_name: pgadmin_container
    build: ./pgadmin
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-root}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped

  server:
    build: ../
    environment:
      DATABASE_URL: "postgresql://postgres:root@localhost:5430/db_test_auth"
      JWT_SECRET: akjDd01L93jsfakcv
      JWT_EXPIRATION_IN: 2h
    ports:
      - 3000:3000


networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:
