version: '3.5'

services:
  prisma_migrate:
    container_name: prisma_migrate
    build:
      context: .
      dockerfile: migrate.Dockerfile
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - DB_HOST=${DB_HOST:-postgres_container}
    env_file:
      - .env
    networks:
      - postgres
    depends_on:
      - db
    restart: unless-stopped

  db:
    container_name: postgres_container
    build: ./postgres
    env_file:
      - .env
    volumes:
      - postgres:${PGDATA:-/data/postgres}
    networks:
      - postgres
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${POSTGRES_USER:-postgres}",
          "-d",
          "${POSTGRES_DB:-postgres_db}"
        ]
    restart: unless-stopped

volumes:
  postgres:


networks:
  postgres:
    driver: bridge
